version: '3.8'

services:

  postgresdb:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database

volumes:
  postgres:

networks:
  mafalda:
    driver: bridge

