FROM python:3.10-alpine
RUN pip3 install --upgrade pip

WORKDIR /kitchen-maintenance-backend
COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY . .
EXPOSE 5000

CMD APP_PROFILE=docker python3 -m src.main

