version: '3.8'

services:

  postgresdb:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database
    networks:
      - mafalda

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile_backend
    image: home-backend
    container_name: home-backend
    ports:
      - "5000:5000"
    networks:
      - mafalda

volumes:
  postgresData:

networks:
  mafalda:
    driver: bridge

