name: Home-Maintenance

on:
  push:
    branches:
      - "github_actions"
      - "main"

  pull_request:
    branches:
      - "github_actions"
      - "main"


jobs:
  build:

    runs-on: ubuntu-latest
    environment: Home-Maintenance
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: '${{secrets.POSTGRES_USER}}'
          POSTGRES_PASSWORD: '${{secrets.POSTGRES_PASSWORD}}'
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5



    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create .env.test file
        env:
          SECRET_KEY: '${{secrets.SECRET_KEY}}'
          POSTGRES_USER: '${{secrets.POSTGRES_USER}}'
          POSTGRES_PASSWORD: '${{secrets.POSTGRES_PASSWORD}}'
        run: |
          echo "SECRET_KEY=${SECRET_KEY}" >> .env.test
          echo "DB_USER=${POSTGRES_USER}" >> .env.test
          echo "DB_PASSWORD=${POSTGRES_PASSWORD}" >> .env.test
          echo "DB_HOST"="localhost" >> .env.test
          echo "DB_NAME"="test" >> .env.test
          echo "DB_PORT"="5432" >> .env.test
  

      - name: Print .env.test file
        run: |
          echo "Printing .env.test:"
          cat .env.test
     

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Test with pytest
        run: |
          pytest tests/test_service.py
          pytest tests/test_api.py